version: '3.9'

services:
  backend:
    build:
      context: ./app
    volumes:
      - ./app:/app
    ports:
      - "5001:5000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["streamlit", "run", "frontend.py"]
    ports:
      - "8501:8501"
    depends_on:
      - backend

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: alrafikri
      POSTGRES_PASSWORD: password
      POSTGRES_DB: lelesg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
